#!/bin/bash
sudo yum install docker -y
sudo yum install git -y
git clone https://borjakev:Yoloswag123@mcsscm.utm.utoronto.ca:9999/git/409/22f/repo_a3group17.git
sudo systemctl start docker
sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8081
sudo iptables -I INPUT -p tcp --dport 8081 -j ACCEPT
cd repo_a3group17/place/server
sudo docker build -t place .
sudo docker run -p 8080:8080 -p 8081:8081 -d --restart unless-stopped place